In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=aa79454106064d1bdb1fdfbf1a92e38733c35dad949ecca4385cf74b68c7c6dd
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2
Requirement already satisfied: apyori in /usr/local/lib/python3.12/dist-packages (1.1.2)

In [ ]:
import pandas as pd
import numpy as np
from apyori import apriori

In [ ]:

path = "/content/Market_Basket_Optimisation - Market_Basket_Optimisation (1).csv"
df= pd.read_csv(path)

In [ ]:
df.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.fillna(0,inplace=True)

In [ ]:
df.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
1,chutney,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
2,turkey,avocado,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
3,mineral water,milk,energy bar,whole wheat rice,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
4,low fat yogurt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0

In [ ]:
transactions = []

for i in range(len(df)):
    transactions.append([str(x) for x in df.iloc[i] if str(x) != ''])

In [ ]:
rules = apriori(transactions,
                min_support=0.003,
                min_confidence=0.2,
                min_lift=3,
                min_length=2)

results = list(rules)

In [ ]:
results

[RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004533333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.178127589063795)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417)]),
 RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151)]),
 RelationRecord(items=frozenset({'0', 'chicken', 'light cream'}), support=0.004533333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'0', 'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844), OrderedStatistic(items_base=frozenset({'0', 'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844)]),
 RelationRecord(items=frozenset({'0', 'escalope', 'mushroom cream sauce'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'0', 'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845), OrderedStatistic(items_base=frozenset({'0', 'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'0', 'escalope', 'pasta'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'0', 'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287), OrderedStatistic(items_base=frozenset({'0', 'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'0', 'fromage blanc', 'honey'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'0', 'honey'}), confidence=0.2450980392156863, lift=5.207465422429595), OrderedStatistic(items_base=frozenset({'0', 'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.178127589063795)]),
 RelationRecord(items=frozenset({'0', 'ground beef', 'herb & pepper'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'0', 'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096), OrderedStatistic(items_base=frozenset({'0', 'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'0', 'ground beef', 'tomato sauce'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'0', 'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528), OrderedStatistic(items_base=frozenset({'0', 'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'0', 'olive oil', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'0', 'olive oil'}), confidence=0.20512820512820515, lift=3.1269543464665417), OrderedStatistic(items_base=frozenset({'0', 'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417)]),
 RelationRecord(items=frozenset({'0', 'olive oil', 'whole wheat pasta'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'0', 'olive oil'}), confidence=0.2714932126696833, lift=4.138616046793953), OrderedStatistic(items_base=frozenset({'0', 'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346)]),
 RelationRecord(items=frozenset({'0', 'shrimp', 'pasta'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'0', 'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151), OrderedStatistic(items_base=frozenset({'0', 'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151)]),
 RelationRecord(items=frozenset({'chicken', '0.0', 'light cream'}), support=0.004533333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken', '0.0'}), confidence=0.2905982905982906, lift=4.843304843304844), OrderedStatistic(items_base=frozenset({'0.0', 'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844)]),
 RelationRecord(items=frozenset({'escalope', '0.0', 'mushroom cream sauce'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope', '0.0'}), confidence=0.30069930069930073, lift=3.7903273197390845), OrderedStatistic(items_base=frozenset({'0.0', 'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'pasta', 'escalope', '0.0'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope', '0.0'}), confidence=0.37288135593220345, lift=4.700185158809287), OrderedStatistic(items_base=frozenset({'pasta', '0.0'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey', '0.0'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey', '0.0'}), confidence=0.2450980392156863, lift=5.178127589063795), OrderedStatistic(items_base=frozenset({'fromage blanc', '0.0'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.178127589063795)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper', '0.0'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef', '0.0'}), confidence=0.3234501347708895, lift=3.2915549671393096), OrderedStatistic(items_base=frozenset({'herb & pepper', '0.0'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef', '0.0'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef', '0.0'}), confidence=0.37735849056603776, lift=3.840147461662528), OrderedStatistic(items_base=frozenset({'tomato sauce', '0.0'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'olive oil', '0.0', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil', '0.0'}), confidence=0.20512820512820515, lift=3.120611639881417), OrderedStatistic(items_base=frozenset({'0.0', 'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417)]),
 RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta', '0.0'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil', '0.0'}), confidence=0.2714932126696833, lift=4.130221288078346), OrderedStatistic(items_base=frozenset({'whole wheat pasta', '0.0'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp', '0.0'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp', '0.0'}), confidence=0.3220338983050848, lift=4.514493901473151), OrderedStatistic(items_base=frozenset({'pasta', '0.0'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151)]),
 RelationRecord(items=frozenset({'avocado', 'spaghetti', 'milk'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'avocado', 'spaghetti'}), items_add=frozenset({'milk'}), confidence=0.4166666666666667, lift=3.2150205761316877)]),
 RelationRecord(items=frozenset({'cake', 'milk', 'burgers'}), support=0.0037333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cake', 'milk'}), items_add=frozenset({'burgers'}), confidence=0.27999999999999997, lift=3.2110091743119265)]),
 RelationRecord(items=frozenset({'chocolate', 'turkey', 'burgers'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate', 'turkey'}), items_add=frozenset({'burgers'}), confidence=0.27058823529411763, lift=3.10307609282245)]),
 RelationRecord(items=frozenset({'turkey', 'milk', 'burgers'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'turkey', 'milk'}), items_add=frozenset({'burgers'}), confidence=0.2823529411764706, lift=3.237992444684296)]),
 RelationRecord(items=frozenset({'cake', 'frozen vegetables', 'tomatoes'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cake', 'frozen vegetables'}), items_add=frozenset({'tomatoes'}), confidence=0.2987012987012987, lift=4.366978051188577), OrderedStatistic(items_base=frozenset({'cake', 'tomatoes'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3650793650793651, lift=3.8295038295038295)]),
 RelationRecord(items=frozenset({'cereals', 'ground beef', 'spaghetti'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cereals', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.676470588235294, lift=3.884785154490586), OrderedStatistic(items_base=frozenset({'cereals', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.45999999999999996, lift=4.681139755766621)]),
 RelationRecord(items=frozenset({'ground beef', 'chicken', 'milk'}), support=0.0038666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'chicken'}), items_add=frozenset({'milk'}), confidence=0.4084507042253521, lift=3.151625804207964)]),
 RelationRecord(items=frozenset({'olive oil', 'chicken', 'milk'}), support=0.0036, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'milk'}), items_add=frozenset({'olive oil'}), confidence=0.24324324324324323, lift=3.7004550189134364), OrderedStatistic(items_base=frozenset({'olive oil', 'chicken'}), items_add=frozenset({'milk'}), confidence=0.5, lift=3.858024691358025), OrderedStatistic(items_base=frozenset({'olive oil', 'milk'}), items_add=frozenset({'chicken'}), confidence=0.21093749999999997, lift=3.5156249999999996)]),
 RelationRecord(items=frozenset({'spaghetti', 'olive oil', 'chicken'}), support=0.0034666666666666665, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti', 'chicken'}), items_add=frozenset({'olive oil'}), confidence=0.20155038759689922, lift=3.0661823670927872)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'chocolate', 'shrimp'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'chocolate'}), items_add=frozenset({'shrimp'}), confidence=0.23255813953488372, lift=3.260160834601174), OrderedStatistic(items_base=frozenset({'chocolate', 'shrimp'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29629629629629634, lift=3.1080031080031083)]),
 RelationRecord(items=frozenset({'ground beef', 'chocolate', 'herb & pepper'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate', 'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.4411764705882353, lift=4.489584164737808)]),
 RelationRecord(items=frozenset({'soup', 'chocolate', 'milk'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup', 'chocolate'}), items_add=frozenset({'milk'}), confidence=0.39473684210526316, lift=3.045808966861599)]),
 RelationRecord(items=frozenset({'spaghetti', 'ground beef', 'cooking oil'}), support=0.0048, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'cooking oil'}), items_add=frozenset({'spaghetti'}), confidence=0.5714285714285714, lift=3.281557646029315), OrderedStatistic(items_base=frozenset({'spaghetti', 'cooking oil'}), items_add=frozenset({'ground beef'}), confidence=0.30252100840336127, lift=3.0785719986773534)]),
 RelationRecord(items=frozenset({'eggs', 'ground beef', 'herb & pepper'}), support=0.0041333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'ground beef'}), items_add=frozenset({'herb & pepper'}), confidence=0.20666666666666667, lift=4.177897574123989), OrderedStatistic(items_base=frozenset({'eggs', 'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.32978723404255317, lift=3.3560437656976236)]),
 RelationRecord(items=frozenset({'eggs', 'spaghetti', 'red wine'}), support=0.0037333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'red wine'}), items_add=frozenset({'spaghetti'}), confidence=0.5283018867924528, lift=3.0338929180271026)]),
 RelationRecord(items=frozenset({'french fries', 'ground beef', 'herb & pepper'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french fries', 'ground beef'}), items_add=frozenset({'herb & pepper'}), confidence=0.23076923076923078, lift=4.665146174580137), OrderedStatistic(items_base=frozenset({'french fries', 'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.46153846153846156, lift=4.6967957415718615)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'green tea', 'tomatoes'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'green tea'}), items_add=frozenset({'tomatoes'}), confidence=0.2314814814814815, lift=3.3842321854017765)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'spaghetti', 'ground beef'}), support=0.008666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3110047846889952, lift=3.164906221394116)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'olive oil', 'milk'}), support=0.0048, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'milk'}), items_add=frozenset({'olive oil'}), confidence=0.20338983050847456, lift=3.094165778526489), OrderedStatistic(items_base=frozenset({'frozen vegetables', 'olive oil'}), items_add=frozenset({'milk'}), confidence=0.4235294117647058, lift=3.26797385620915)]),
 RelationRecord(items=frozenset({'soup', 'frozen vegetables', 'milk'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup', 'frozen vegetables'}), items_add=frozenset({'milk'}), confidence=0.5, lift=3.858024691358025)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'milk', 'tomatoes'}), support=0.0041333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'tomatoes'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29523809523809524, lift=3.096903096903097)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'shrimp', 'mineral water'}), support=0.0072, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shrimp', 'mineral water'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3068181818181818, lift=3.2183725365543547)]),
 RelationRecord(items=frozenset({'spaghetti', 'frozen vegetables', 'olive oil'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'olive oil'}), confidence=0.20574162679425836, lift=3.1299436124887174)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'spaghetti', 'shrimp'}), support=0.006, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'shrimp'}), confidence=0.21531100478468898, lift=3.0183785717479763)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'shrimp', 'tomatoes'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'shrimp'}), items_add=frozenset({'tomatoes'}), confidence=0.24000000000000002, lift=3.5087719298245617), OrderedStatistic(items_base=frozenset({'frozen vegetables', 'tomatoes'}), items_add=frozenset({'shrimp'}), confidence=0.24793388429752067, lift=3.475708658376458), OrderedStatistic(items_base=frozenset({'shrimp', 'tomatoes'}), items_add=frozenset({'frozen vegetables'}), confidence=0.35714285714285715, lift=3.746253746253746)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'spaghetti', 'tomatoes'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'tomatoes'}), confidence=0.23923444976076555, lift=3.497579674864993), OrderedStatistic(items_base=frozenset({'spaghetti', 'tomatoes'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3184713375796178, lift=3.340608436149837)]),
 RelationRecord(items=frozenset({'spaghetti', 'ground beef', 'grated cheese'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti', 'grated cheese'}), items_add=frozenset({'ground beef'}), confidence=0.3225806451612903, lift=3.282706701098612)]),
 RelationRecord(items=frozenset({'ground beef', 'green tea', 'tomatoes'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'green tea'}), items_add=frozenset({'tomatoes'}), confidence=0.2072072072072072, lift=3.0293451346082922)]),

In [ ]:
rows = []

for item in results:
    pair = item.items
    support = item.support

    for stat in item.ordered_statistics:
        lhs = ', '.join(stat.items_base)
        rhs = ', '.join(stat.items_add)
        confidence = stat.confidence
        lift = stat.lift

        rows.append([lhs, rhs, support, confidence, lift])

df_final = pd.DataFrame(rows, columns=['lhs','rhs','support','confidence','lift'])
df_final.head()

                    lhs          rhs   support  confidence      lift
0           light cream      chicken  0.004533    0.290598  4.843305
1  mushroom cream sauce     escalope  0.005733    0.300699  3.790327
2                 pasta     escalope  0.005867    0.372881  4.700185
3         fromage blanc        honey  0.003333    0.245098  5.178128
4         herb & pepper  ground beef  0.016000    0.323450  3.291555

In [ ]:
df_final.sort_values('lift', ascending=False).head(10)

,lhs,rhs,support,confidence,lift
1077,"0, soup, frozen vegetables","milk, mineral water, 0.0",0.003067,0.383333,7.986111
1075,"soup, frozen vegetables","0, milk, mineral water, 0.0",0.003067,0.383333,7.986111
436,"soup, frozen vegetables","milk, mineral water",0.003067,0.383333,7.986111
781,"soup, frozen vegetables","0, milk, mineral water",0.003067,0.383333,7.986111
1085,"0, soup, frozen vegetables, 0.0","milk, mineral water",0.003067,0.383333,7.986111
783,"0, soup, frozen vegetables","milk, mineral water",0.003067,0.383333,7.986111
1079,"soup, frozen vegetables, 0.0","0, milk, mineral water",0.003067,0.383333,7.986111
895,"soup, frozen vegetables, 0.0","milk, mineral water",0.003067,0.383333,7.986111
893,"soup, frozen vegetables","milk, mineral water, 0.0",0.003067,0.383333,7.986111
774,"0, frozen vegetables, olive oil","milk, mineral water",0.003333,0.297619,6.200397

In [ ]:
transactions = []

for i in range(0,len(df)):
    transactions.append([str(df.values[i,j]) for j in range(0,20) if str(df.values[i,j])!='0'])

transactions[0]
transactions[1]

['chutney', '0.0']

In [ ]:
rules = apriori(transactions, min_support=0.003, min_confidence=0.2, min_lift=3, min_length=2)

Results = list(rules)
Results

[RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004533333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.178127589063795)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151)]),
 RelationRecord(items=frozenset({'0.0', 'light cream', 'chicken'}), support=0.004533333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'0.0', 'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844), OrderedStatistic(items_base=frozenset({'0.0', 'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844)]),
 RelationRecord(items=frozenset({'0.0', 'mushroom cream sauce', 'escalope'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'0.0', 'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845), OrderedStatistic(items_base=frozenset({'0.0', 'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'0.0', 'pasta', 'escalope'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'0.0', 'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287), OrderedStatistic(items_base=frozenset({'0.0', 'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'fromage blanc', '0.0', 'honey'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'0.0', 'honey'}), confidence=0.2450980392156863, lift=5.178127589063795), OrderedStatistic(items_base=frozenset({'fromage blanc', '0.0'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.178127589063795)]),
 RelationRecord(items=frozenset({'herb & pepper', '0.0', 'ground beef'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'0.0', 'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096), OrderedStatistic(items_base=frozenset({'herb & pepper', '0.0'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'0.0', 'tomato sauce', 'ground beef'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'0.0', 'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528), OrderedStatistic(items_base=frozenset({'0.0', 'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'olive oil', '0.0', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'0.0', 'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417), OrderedStatistic(items_base=frozenset({'0.0', 'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417)]),
 RelationRecord(items=frozenset({'whole wheat pasta', '0.0', 'olive oil'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'0.0', 'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346), OrderedStatistic(items_base=frozenset({'whole wheat pasta', '0.0'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346)]),
 RelationRecord(items=frozenset({'shrimp', '0.0', 'pasta'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp', '0.0'}), confidence=0.3220338983050848, lift=4.514493901473151), OrderedStatistic(items_base=frozenset({'0.0', 'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151)]),
 RelationRecord(items=frozenset({'milk', 'spaghetti', 'avocado'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti', 'avocado'}), items_add=frozenset({'milk'}), confidence=0.4166666666666667, lift=3.2150205761316877)]),
 RelationRecord(items=frozenset({'milk', 'cake', 'burgers'}), support=0.0037333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'cake'}), items_add=frozenset({'burgers'}), confidence=0.27999999999999997, lift=3.2110091743119265)]),
 RelationRecord(items=frozenset({'turkey', 'burgers', 'chocolate'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'turkey', 'chocolate'}), items_add=frozenset({'burgers'}), confidence=0.27058823529411763, lift=3.10307609282245)]),
 RelationRecord(items=frozenset({'milk', 'turkey', 'burgers'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'turkey'}), items_add=frozenset({'burgers'}), confidence=0.2823529411764706, lift=3.237992444684296)]),
 RelationRecord(items=frozenset({'tomatoes', 'frozen vegetables', 'cake'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'cake'}), items_add=frozenset({'tomatoes'}), confidence=0.2987012987012987, lift=4.366978051188577), OrderedStatistic(items_base=frozenset({'tomatoes', 'cake'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3650793650793651, lift=3.8295038295038295)]),
 RelationRecord(items=frozenset({'spaghetti', 'ground beef', 'cereals'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'cereals'}), items_add=frozenset({'spaghetti'}), confidence=0.676470588235294, lift=3.884785154490586), OrderedStatistic(items_base=frozenset({'spaghetti', 'cereals'}), items_add=frozenset({'ground beef'}), confidence=0.45999999999999996, lift=4.681139755766621)]),
 RelationRecord(items=frozenset({'milk', 'ground beef', 'chicken'}), support=0.0038666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'chicken'}), items_add=frozenset({'milk'}), confidence=0.4084507042253521, lift=3.151625804207964)]),
 RelationRecord(items=frozenset({'milk', 'olive oil', 'chicken'}), support=0.0036, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'chicken'}), items_add=frozenset({'olive oil'}), confidence=0.24324324324324323, lift=3.7004550189134364), OrderedStatistic(items_base=frozenset({'olive oil', 'chicken'}), items_add=frozenset({'milk'}), confidence=0.5, lift=3.858024691358025), OrderedStatistic(items_base=frozenset({'milk', 'olive oil'}), items_add=frozenset({'chicken'}), confidence=0.21093749999999997, lift=3.5156249999999996)]),
 RelationRecord(items=frozenset({'spaghetti', 'olive oil', 'chicken'}), support=0.0034666666666666665, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti', 'chicken'}), items_add=frozenset({'olive oil'}), confidence=0.20155038759689922, lift=3.0661823670927872)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'shrimp', 'chocolate'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'chocolate'}), items_add=frozenset({'shrimp'}), confidence=0.23255813953488372, lift=3.260160834601174), OrderedStatistic(items_base=frozenset({'shrimp', 'chocolate'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29629629629629634, lift=3.1080031080031083)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef', 'chocolate'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper', 'chocolate'}), items_add=frozenset({'ground beef'}), confidence=0.4411764705882353, lift=4.489584164737808)]),
 RelationRecord(items=frozenset({'milk', 'soup', 'chocolate'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup', 'chocolate'}), items_add=frozenset({'milk'}), confidence=0.39473684210526316, lift=3.045808966861599)]),
 RelationRecord(items=frozenset({'spaghetti', 'cooking oil', 'ground beef'}), support=0.0048, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cooking oil', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.5714285714285714, lift=3.281557646029315), OrderedStatistic(items_base=frozenset({'spaghetti', 'cooking oil'}), items_add=frozenset({'ground beef'}), confidence=0.30252100840336127, lift=3.0785719986773534)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef', 'eggs'}), support=0.0041333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'eggs'}), items_add=frozenset({'herb & pepper'}), confidence=0.20666666666666667, lift=4.177897574123989), OrderedStatistic(items_base=frozenset({'herb & pepper', 'eggs'}), items_add=frozenset({'ground beef'}), confidence=0.32978723404255317, lift=3.3560437656976236)]),
 RelationRecord(items=frozenset({'spaghetti', 'red wine', 'eggs'}), support=0.0037333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red wine', 'eggs'}), items_add=frozenset({'spaghetti'}), confidence=0.5283018867924528, lift=3.0338929180271026)]),
 RelationRecord(items=frozenset({'herb & pepper', 'french fries', 'ground beef'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french fries', 'ground beef'}), items_add=frozenset({'herb & pepper'}), confidence=0.23076923076923078, lift=4.665146174580137), OrderedStatistic(items_base=frozenset({'herb & pepper', 'french fries'}), items_add=frozenset({'ground beef'}), confidence=0.46153846153846156, lift=4.6967957415718615)]),
 RelationRecord(items=frozenset({'tomatoes', 'frozen vegetables', 'green tea'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'green tea'}), items_add=frozenset({'tomatoes'}), confidence=0.2314814814814815, lift=3.3842321854017765)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'spaghetti', 'ground beef'}), support=0.008666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3110047846889952, lift=3.164906221394116)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'olive oil', 'milk'}), support=0.0048, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'milk'}), items_add=frozenset({'olive oil'}), confidence=0.20338983050847456, lift=3.094165778526489), OrderedStatistic(items_base=frozenset({'frozen vegetables', 'olive oil'}), items_add=frozenset({'milk'}), confidence=0.4235294117647058, lift=3.26797385620915)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'soup', 'milk'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'soup'}), items_add=frozenset({'milk'}), confidence=0.5, lift=3.858024691358025)]),
 RelationRecord(items=frozenset({'tomatoes', 'frozen vegetables', 'milk'}), support=0.0041333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomatoes', 'milk'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29523809523809524, lift=3.096903096903097)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'mineral water', 'shrimp'}), support=0.0072, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'shrimp'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3068181818181818, lift=3.2183725365543547)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'spaghetti', 'olive oil'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'olive oil'}), confidence=0.20574162679425836, lift=3.1299436124887174)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'shrimp', 'spaghetti'}), support=0.006, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'shrimp'}), confidence=0.21531100478468898, lift=3.0183785717479763)]),
 RelationRecord(items=frozenset({'tomatoes', 'frozen vegetables', 'shrimp'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'shrimp'}), items_add=frozenset({'tomatoes'}), confidence=0.24000000000000002, lift=3.5087719298245617), OrderedStatistic(items_base=frozenset({'tomatoes', 'frozen vegetables'}), items_add=frozenset({'shrimp'}), confidence=0.24793388429752067, lift=3.475708658376458), OrderedStatistic(items_base=frozenset({'tomatoes', 'shrimp'}), items_add=frozenset({'frozen vegetables'}), confidence=0.35714285714285715, lift=3.746253746253746)]),
 RelationRecord(items=frozenset({'tomatoes', 'frozen vegetables', 'spaghetti'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'spaghetti'}), items_add=frozenset({'tomatoes'}), confidence=0.23923444976076555, lift=3.497579674864993), OrderedStatistic(items_base=frozenset({'tomatoes', 'spaghetti'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3184713375796178, lift=3.340608436149837)]),
 RelationRecord(items=frozenset({'spaghetti', 'ground beef', 'grated cheese'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti', 'grated cheese'}), items_add=frozenset({'ground beef'}), confidence=0.3225806451612903, lift=3.282706701098612)]),
 RelationRecord(items=frozenset({'tomatoes', 'green tea', 'ground beef'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green tea', 'ground beef'}), items_add=frozenset({'tomatoes'}), confidence=0.2072072072072072, lift=3.0293451346082922)]),
 RelationRecord(items=frozenset({'herb & pepper', 'milk', 'ground beef'}), support=0.0036, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper', 'milk'}), items_add=frozenset({'ground beef'}), confidence=0.391304347826087, lift=3.982065954810926)]),
 RelationRecord(items=frozenset({'herb & pepper', 'mineral water', 'ground beef'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper', 'mineral water'}), items_add=frozenset({'ground beef'}), confidence=0.390625, lift=3.975152645861601)]),
 RelationRecord(items=frozenset({'herb & pepper', 'spaghetti', 'ground beef'}), support=0.0064, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3934426229508197, lift=4.003825878061259)]),
 RelationRecord(items=frozenset({'milk', 'olive oil', 'ground beef'}), support=0.004933333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'ground beef'}), items_add=frozenset({'olive oil'}), confidence=0.22424242424242424, lift=3.411395906324912)]),
 RelationRecord(items=frozenset({'milk', 'soup', 'ground beef'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup', 'ground beef'}), items_add=frozenset({'milk'}), confidence=0.410958904109589, lift=3.170979198376459)]),
 RelationRecord(items=frozenset({'pepper', 'spaghetti', 'ground beef'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pepper', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3378378378378379, lift=3.4379698558803042)]),
 RelationRecord(items=frozenset({'spaghetti', 'shrimp', 'ground beef'}), support=0.006, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shrimp', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.5232558139534884, lift=3.004914704939635)]),
 RelationRecord(items=frozenset({'spaghetti', 'tomato sauce', 'ground beef'}), support=0.0030666666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'spaghetti', 'ground beef'}), confidence=0.2169811320754717, lift=5.535232961108973), OrderedStatistic(items_base=frozenset({'tomato sauce', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.5750000000000001, lift=3.302067381316999), OrderedStatistic(items_base=frozenset({'spaghetti', 'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.48936170212765956, lift=4.979935910390022)]),
 RelationRecord(items=frozenset({'spaghetti', 'mineral water', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'spaghetti', 'mineral water'}), confidence=0.20512820512820515, lift=3.4340659340659343)]),
 RelationRecord(items=frozenset({'milk', 'shrimp', 'olive oil'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shrimp', 'olive oil'}), items_add=frozenset({'milk'}), confidence=0.4, lift=3.08641975308642)]),
 RelationRecord(items=frozenset({'milk', 'soup', 'olive oil'}), support=0.0036, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'olive oil'}), items_add=frozenset({'soup'}), confidence=0.21093749999999997, lift=4.174224934036939), OrderedStatistic(items_base=frozenset({'milk', 'soup'}), items_add=frozenset({'olive oil'}), confidence=0.23684210526315788, lift=3.603074623678872), OrderedStatistic(items_base=frozenset({'soup', 'olive oil'}), items_add=frozenset({'milk'}), confidence=0.40298507462686567, lift=3.109452736318408)]),
 RelationRecord(items=frozenset({'milk', 'spaghetti', 'olive oil'}), support=0.0072, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'spaghetti'}), items_add=frozenset({'olive oil'}), confidence=0.20300751879699247, lift=3.0883496774390333)]),

In [ ]:
df_results = pd.DataFrame(Results)
df_results.head()

support = df_results.support

In [ ]:
first_values = []
second_values = []
third_values = []
fourth_value = []

for i in range(df_results.shape[0]):
    single_list = df_results['ordered_statistics'][i][0]
    first_values.append(list(single_list[0]))
    second_values.append(list(single_list[1]))
    third_values.append(single_list[2])
    fourth_value.append(single_list[3])

In [ ]:
lhs = pd.DataFrame(first_values)
rhs = pd.DataFrame(second_values)
confidence=pd.DataFrame(third_values,columns=['confidence'])
lift=pd.DataFrame(fourth_value,columns=['lift'])

In [ ]:
df_final = pd.concat([lhs,rhs,support,confidence,lift], axis=1)

df_final.fillna(value=' ', inplace=True)
df_final.head()

,0,1,2,0,1,2,support,confidence,lift
0,light cream,,,chicken,,,0.004533,0.290598,4.843305
1,mushroom cream sauce,,,escalope,,,0.005733,0.300699,3.790327
2,pasta,,,escalope,,,0.005867,0.372881,4.700185
3,fromage blanc,,,honey,,,0.003333,0.245098,5.178128
4,herb & pepper,,,ground beef,,,0.016000,0.323450,3.291555

In [ ]:
df_final['lhs'] = df_final['lhs_item_1'] + str(', ') + df_final['lhs_item_2'] + str(', ') + df_final['lhs_item_3']
df_final['rhs'] = df_final['rhs_item_1'] + str(', ') + df_final['rhs_item_2'] + str(', ') + df_final['rhs_item_3']

df_final['lhs'] = df_final['lhs'].str.replace(',   ,  ', '').str.replace(',  ', ', ').str.strip()
df_final['rhs'] = df_final['rhs'].str.replace(',   ,  ', '').str.replace(',  ', ', ').str.strip()

df_final.head()

,lhs_item_1,lhs_item_2,lhs_item_3,rhs_item_1,rhs_item_2,rhs_item_3,support,confidence,lift,lhs,rhs
0,"light cream,",,", chicken,",chicken,,,0.004533,0.290598,4.843305,"light cream, , , , chicken,","chicken, ,"
1,"mushroom cream sauce,",,", escalope,",escalope,,,0.005733,0.300699,3.790327,"mushroom cream sauce, , , , escalope,","escalope, ,"
2,"pasta,",,", escalope,",escalope,,,0.005867,0.372881,4.700185,"pasta, , , , escalope,","escalope, ,"
3,"fromage blanc,",,", honey,",honey,,,0.003333,0.245098,5.178128,"fromage blanc, , , , honey,","honey, ,"
4,"herb & pepper,",,", ground beef,",ground beef,,,0.016000,0.323450,3.291555,"herb & pepper, , , , ground beef,","ground beef, ,"

In [ ]:
df_final.columns = ['lhs_item_1','lhs_item_2','lhs_item_3','rhs_item_1','rhs_item_2','rhs_item_3','support','confidence','lift']
df_final.head()

,lhs_item_1,lhs_item_2,lhs_item_3,rhs_item_1,rhs_item_2,rhs_item_3,support,confidence,lift
0,"light cream,",,", chicken,",chicken,,,0.004533,0.290598,4.843305
1,"mushroom cream sauce,",,", escalope,",escalope,,,0.005733,0.300699,3.790327
2,"pasta,",,", escalope,",escalope,,,0.005867,0.372881,4.700185
3,"fromage blanc,",,", honey,",honey,,,0.003333,0.245098,5.178128
4,"herb & pepper,",,", ground beef,",ground beef,,,0.016000,0.323450,3.291555

In [ ]:
df_final.drop(columns=['lhs_item_1','lhs_item_2','lhs_item_3','rhs_item_1','rhs_item_2','rhs_item_3'],inplace=True)

df_final.head()

,support,confidence,lift,lhs,rhs
0,0.004533,0.290598,4.843305,"light cream, , , , chicken,","chicken, ,"
1,0.005733,0.300699,3.790327,"mushroom cream sauce, , , , escalope,","escalope, ,"
2,0.005867,0.372881,4.700185,"pasta, , , , escalope,","escalope, ,"
3,0.003333,0.245098,5.178128,"fromage blanc, , , , honey,","honey, ,"
4,0.016000,0.323450,3.291555,"herb & pepper, , , , ground beef,","ground beef, ,"

In [ ]:
df_final.sort_values('lift', ascending=False).head(10)

,support,confidence,lift,lhs,rhs
126,0.003067,0.383333,7.986111,"frozen vegetables, soup, soup, , milk, mineral...","milk, mineral water,"
150,0.003067,0.383333,7.986111,"frozen vegetables, soup, soup, , milk, mineral...","milk, mineral water, 0.0"
149,0.003333,0.294118,6.127451,"frozen vegetables, olive oil, olive oil, , mil...","milk, mineral water, 0.0"
125,0.003333,0.294118,6.127451,"frozen vegetables, olive oil, olive oil, , mil...","milk, mineral water,"
108,0.003867,0.402778,6.127451,"whole wheat pasta, mineral water, mineral wate...","0.0, olive oil,"
61,0.003867,0.402778,6.127451,"whole wheat pasta, mineral water, mineral wate...","olive oil, ,"
53,0.003067,0.216981,5.535233,"tomato sauce, , , , spaghetti, ground beef","spaghetti, ground beef,"
100,0.003067,0.216981,5.535233,"tomato sauce, , , , spaghetti, 0.0","spaghetti, 0.0, ground beef"
3,0.003333,0.245098,5.178128,"fromage blanc, , , , honey,","honey, ,"
12,0.003333,0.245098,5.178128,"fromage blanc, , , , 0.0, honey","0.0, honey,"