In [ ]:
import pandas  as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
path="/content/heart - heart.csv"
df=pd.read_csv(path)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [ ]:
X= df.drop("target",axis=1)
y=df["target"]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
clf.fit(X_train,y_train);

In [ ]:
y_preds = clf.predict(X_test)
y_preds

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1])

In [ ]:
y_test

58     0
584    0
115    0
144    1
465    1
      ..
199    0
655    1
27     0
155    1
494    1
Name: target, Length: 205, dtype: int64

In [ ]:
clf.score(X_train, y_train)

1.0

In [ ]:
clf.score(X_test, y_test)

1.0

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        92
           1       1.00      1.00      1.00       113

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

In [ ]:
confusion_matrix(y_test, y_preds)

array([[ 92,   0],
       [  0, 113]])

In [ ]:
accuracy_score(y_test, y_preds)

1.0

In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

for i in range(1, 22, 1):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 1 estimators...
Model accuracy on test set: 91.22%

Trying model with 2 estimators...
Model accuracy on test set: 95.61%

Trying model with 3 estimators...
Model accuracy on test set: 98.05%

Trying model with 4 estimators...
Model accuracy on test set: 98.54%

Trying model with 5 estimators...
Model accuracy on test set: 98.54%

Trying model with 6 estimators...
Model accuracy on test set: 98.54%

Trying model with 7 estimators...
Model accuracy on test set: 100.00%

Trying model with 8 estimators...
Model accuracy on test set: 98.54%

Trying model with 9 estimators...
Model accuracy on test set: 100.00%

Trying model with 10 estimators...
Model accuracy on test set: 97.56%

Trying model with 11 estimators...
Model accuracy on test set: 97.56%

Trying model with 12 estimators...
Model accuracy on test set: 98.54%

Trying model with 13 estimators...
Model accuracy on test set: 97.56%

Trying model with 14 estimators...
Model accuracy on test set: 97.56%

Trying model with 15 estimators...
Model accuracy on test set: 100.00%

Trying model with 16 estimators...
Model accuracy on test set: 98.54%

Trying model with 17 estimators...
Model accuracy on test set: 99.02%

Trying model with 18 estimators...
Model accuracy on test set: 98.54%

Trying model with 19 estimators...
Model accuracy on test set: 97.56%

Trying model with 20 estimators...
Model accuracy on test set: 98.54%

Trying model with 21 estimators...
Model accuracy on test set: 98.54%